server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          host: nuc
          __path__: /var/log/nginx/*log

  - job_name: systemd
    journal:
      max_age: 12h
      path: /run/log/journal
      labels:
        job: systemd
        host: nuc
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: 'hostname'

  - job_name: grafana
    static_configs:
      - targets:
          - localhost
        labels:
          job: grafana
          compose_service: grafana
          host: nuc
          __path__: /var/lib/grafana/log/*.log
